<footer>
            <hr>
		
            <a href="http://www.swinburne.edu.au"><img src="images/logo.png" alt="Swinburne University Technology"></a>&emsp;&emsp;
            <p id="contactus">	Message our Team: <br>
	          	<a href="mailto:104002288@student.swin.edu.au">Winston Li</a>
            	<a href="mailto:103989487@student.swin.edu.au">Amber Biezen</a>
            	<a href="mailto:104002288@student.swin.edu.au">Storm Howard</a>
            	<a href="mailto:103864526@student.swin.edu.au">Brandy Dan</a>
            	<a href="mailto:103643291@student.swin.edu.au">Doris Feng</a></p>
        </footer>